[project]
name = "eva-rwa"
version = "0.1.0"
description = "Interface Real World Asset et IoT pour E.V.A."
dependencies = [
    "fastapi",
    "uvicorn",
    "paho-mqtt",
    "web3",
    "python-dotenv"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
